#include <windows.h>
#include <iostream>
#include <algorithm>
#include <vector>
#include <string>
#include <assert.h>
#include <cassert>
#include <tlhelp32.h>
#include <psapi.h>
#include <tchar.h>
#include <csignal>
#include <Oleacc.h>
#include <ctime>
#include <time.h>
#include <Aclapi.h>
#include "sddl.h"
#include <QtNetwork/QNetworkAccessManager>
#include <QtNetwork/QNetworkReply>
#include <QStringList>
#include <QMovie>
#include <QMessageBox>
